import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/home.module.scss';

export default function Home() {
  return (
    <div className={styles.home}>
      <Head>
        <title>Jeremy Philemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.message}>Hello World!</div>
    </div>
  );
}
